### ISSUE TITLE
Social media page should open in new tab

### ISSUE THREAD

**Issue by shyamsitaula** [aryan78/dpch#12]
Social media pages should open in new tab when user clicks the button. 

However it is opening in the current page.

**Comment by aryan78** [comment]
This issue is fixed!

**Comment by aryan78** [comment]
**Fixed.**


RCA - Wordrpress configuration error

Had to some settings in dashboard as seen in screenshot below.

![ss](https://user-images.githubusercontent.com/41724847/45531845-584a0180-b811-11e8-9146-f3f263dafc54.png)
![ss 1](https://user-images.githubusercontent.com/41724847/45531855-613ad300-b811-11e8-8f59-a6a0ed73f193.png)
