### ISSUE TITLE
Contact section unnecessary divider

### ISSUE THREAD

**Issue by shyamsitaula** [aryan78/dpch#4]
![issue 3](https://user-images.githubusercontent.com/41724847/44901554-713db780-ad27-11e8-94e6-79fb94874422.png)
**Page: Contact**

There is a divider between contact section intro text and form sections. There should not be any divider.

**Comment by aryan78** [comment]
This issue is solved 
![issue 3solved](https://user-images.githubusercontent.com/41724847/44901619-a0542900-ad27-11e8-86bc-9cfc05dff1f9.png)
