### ISSUE TITLE
Database 

### ISSUE THREAD

**Issue by aryan78** [aryan78/dpch#5]
The content inside the table named person is not displayed properly.
![screenshot from 2018-09-02 17-31-20](https://user-images.githubusercontent.com/41724847/44955632-3463f300-aed6-11e8-8e59-d1d85ce10fa7.png)

**Comment by shyamsitaula** [comment]
You need to remove the trailing \n from the string before inserting into sql database.

**Comment by aryan78** [comment]
Fixed! 
RCA : Code
