### ISSUE TITLE
Password should not be in file

### ISSUE THREAD

**Issue by shyamsitaula** [aryan78/dpch#6]
**File: dbconn.php**

scripts/dbconn.php has sql login credentials. 

**Exptected Result:**

$username and $password should be empty strings.

**Actual:**

$username and $password have actual values.

**Comment by shyamsitaula** [comment]
We can write a bash sript to update ths file.

User will run that script to put sql username and password information in dbconn.php if needed.

**Comment by aryan78** [comment]
Tracking this issue in another repo
