### ISSUE TITLE
Footer social icons need to link to correct page

### ISSUE THREAD

**Issue by shyamsitaula** [aryan78/dpch#8]
Social media icons in footer should link to appropriate page. Right now they link to some wordpress page.

**Comment by shyamsitaula** [comment]
Same issue in below pages:

1. Home
2. Contact
3. NSU

**Comment by shyamsitaula** [comment]
It seems only the social media buttons in the **footer** are linked to correct page (SA team page for now).

However social media buttons in Home, NSU, and Contact pages are not linked to appropriate page. Please fix this as well.

**Comment by aryan78** [comment]
The social media icons in all the pages are linked to the correct page (SA team page for now).
