### ISSUE TITLE
Test Contact page forms

### ISSUE THREAD

**Issue by shyamsitaula** [aryan78/dpch#9]
Test and verify that submitted forms are received in the expected email addresses.

**Comment by shyamsitaula** [comment]
Also do same test in NSU page.

**Comment by aryan78** [comment]
All the forms function properly and the messages are received in the given email address. 
![form](https://user-images.githubusercontent.com/41724847/45347956-0dd84300-b5cd-11e8-9a7e-6e3d00a8a24d.png)
![from](https://user-images.githubusercontent.com/41724847/45347978-16307e00-b5cd-11e8-9330-3fbdcc5cd4cb.png)
